// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const CardVertical: string;
export const CardAction: string;
export const VerticalCard: string;
