// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const CardHorizontal: string;
export const CardHorizontalImage: string;
export const CardAction: string;
