// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const labelContainer: string;
export const labelContainerLeft: string;
export const labelContainerRight: string;
export const labelContainerTop: string;
export const labelContainerBottom: string;
export const container: string;
export const containerActive: string;
export const containerInactive: string;
export const toggle: string;
export const toggleActive: string;
export const toggleInactive: string;
